# Generated by Django 2.1.13 on 2019-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
