# Generated by Django 2.1.13 on 2019-11-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tb_grade',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10, unique=True)),
                ('s_age', models.IntegerField(default=18)),
                ('a_gender', models.BooleanField(default=1)),
                ('s_create_time', models.DateTimeField(auto_now_add=True)),
                ('c', models.ManyToManyField(to='app2.Course')),
                ('g', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s', to='app2.Grade')),
            ],
            options={
                'db_table': 'tb_student',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_addr', models.CharField(max_length=100, null=True)),
                ('s_phone', models.CharField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'tb_student_info',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='app2.StudentInfo'),
        ),
    ]
