# Generated by Django 2.1.13 on 2019-11-15 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='g',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.Grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.StudentInfo'),
        ),
    ]
