# Generated by Django 2.1.13 on 2019-11-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20191115_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='imgs')),
            ],
            options={
                'db_table': 'tb_user_images',
            },
        ),
    ]
