# Generated by Django 2.1.13 on 2019-11-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
